### ISSUE TITLE
[BUG] Check all Figures and Graphs to Ensure showing Chinese Characters

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-intro.zh-cn#61]
Once all PRs are merged we should do a review of all figures and graphs to ensure chinese characters are showing up as intended. 

We can use the fix that Humphrey identified. 

https://github.com/QuantEcon/lecture-intro.zh-cn/issues/30#issuecomment-2367889578

**Comment by SylviaZhaooo** [comment]
Hi Matt,

Thanks for merging. I have translated all the lectures assigned to me and used the code provided by Humphrey to ensure the Chinese characters are displayed correctly. However, some words and labels were not initially translated due to the code. (For example, some code sets the titles at the beginning, preventing the AI from translating them right away.) I will check these issues today and tomorrow to make sure this won’t be a problem.

Best,
Sylvia

**Comment by mmcky** [comment]
I have seen this rolled out pretty widely so closing this issue now.
